version: '3.8'

services:
  mysql:
    build:
      context: ./docker/mysql
    container_name: ${NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
#    volumes:
      #- ./db-data:/var/lib/mysql
    ports:
      - "${MYSQL_SERVER_PORT}:3306"
    restart: always

  php:
    user: "${UID-0}:${GID-0}"
    build:
      context: ./docker/php
    container_name: ${NAME}-php
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ${PROJECT_PATH}:/var/www/${PROJECT_NAME}
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
